language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/ILI9341/RotatingCube
    - PLATFORMIO_CI_SRC=examples/ILI9341/DrawXBM
    - PLATFORMIO_CI_SRC=examples/ILI9341/DrawPaletteImage_4Bit
    - PLATFORMIO_CI_SRC=examples/ILI9341/DrawPaletteImage_1Bit
    - PLATFORMIO_CI_SRC=examples/ILI9341/Carousel
    - PLATFORMIO_CI_SRC=examples/ILI9341/BasicDrawing
    - PLATFORMIO_CI_SRC=examples/EPaper/EPaperDemo2_54Pervasive
    - PLATFORMIO_CI_SRC=examples/EPaper/EPD_WaveShare_2_9

install:
    - pip install -U platformio
    - platformio lib install "XPT2046_Touchscreen" "EspSoftwareSerial@3.4.1"
    - platformio lib update

script:
    - platformio ci --lib="." --board=nodemcuv2
